### ISSUE TITLE
Feature Request: Set endpoint with comment

### ISSUE THREAD

**Issue by minego** [skanehira/denops-graphql.vim#7]
It would be EXTREMELY helpful to be able to include a comment at the top of a file to set the endpoint, rather than having to run the command each time I open a file.

**Comment by skanehira** [comment]
I think it is good idea and will consider it

**Comment by minego** [comment]
> I think it is good idea and will consider it

Thanks! I love this plugin. It has been really useful!

**Comment by skanehira** [comment]
@minego Supported this feature.
Please update plugin :)

**Comment by minego** [comment]
It appears to work beautifully. Thank you.
